# Generated by Django 4.2.2 on 2023-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_category_customer_order_product_delete_record_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Karyawan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                (
                    "pekerjaan",
                    models.CharField(
                        choices=[
                            ("MARKETING", "marketing"),
                            ("ADMIN", "admin"),
                            ("DESAINER POLA", "desainer pola"),
                            ("JAHIT", "jahit"),
                            ("TARIK SOL", "tarik sol"),
                        ],
                        max_length=20,
                    ),
                ),
                ("alamat", models.CharField(blank=True, default="", max_length=250)),
                ("no_hp", models.CharField(blank=True, default="", max_length=13)),
            ],
        ),
    ]
