# Generated by Django 4.2.6 on 2023-10-31 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_gajian"),
    ]

    operations = [
        migrations.CreateModel(
            name="GajianKaryawan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pekerjaan",
                    models.CharField(
                        choices=[
                            ("MARKETING", "marketing"),
                            ("ADMIN", "admin"),
                            ("DESAINER POLA", "desainer pola"),
                            ("JAHIT", "jahit"),
                            ("TARIK SOL", "tarik sol"),
                        ],
                        max_length=20,
                    ),
                ),
                ("qty", models.IntegerField()),
                (
                    "nama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.karyawan",
                    ),
                ),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.product",
                    ),
                ),
            ],
        ),
    ]
